### ISSUE TITLE
Tjeneste for å transformere Altinn modeller

### ISSUE THREAD

**Issue by lillelars** [Informasjonsforvaltning/altinn-model-publisher#1]
I dag finnes det en tjeneste som henter informasjonsmodeller fra Altinn og transformerer de slik at vi kan presentere de.

Vi ønsker å utvikle en ny tjeneste som benytter et eget biblioteket til å transformere Altinn modeller til ttl-format slik at vi kan høste de på modelcat-ap-no formatet.

**Comment by shenluna** [comment]
altinn-model-publisher er pensjonert. Lukker dermed denne epicen og tilhørende tasks.
