### ISSUE TITLE
Egenskaper som peker til interne objekter får samme seres:guid som objektet

### ISSUE THREAD

**Issue by NilsOveTen** [Informasjonsforvaltning/altinn-model-publisher#35]

**Comment by shenluna** [comment]
Testet i staging

https://staging.fellesdatakatalog.digdir.no/informationmodels/a8711d9f-ad87-4adc-8502-158f715ffec0
![image](https://user-images.githubusercontent.com/73637969/105847035-5c8ba980-5fdd-11eb-9698-6c4a53f4ee7d.png)
